default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cineroom_development

test:
  <<: *default
  database: cineroom_test

production:
  primary: &primary_production
    <<: *default
    database: cineroom_production
    username: cineroom
    password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: cineroom_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: cineroom_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: cineroom_production_cable
    migrations_paths: db/cable_migrate
